create table if not exists public.supplies (
  id bigint generated by default as identity primary key,
  type text not null,
  product_id bigint references public.products(id) on delete set null,
  qty integer not null default 0,
  supplier_id bigint references public.suppliers(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  note text,
  created_at timestamptz default now()
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  type text not null,
  action text not null,
  user_id uuid references auth.users(id) on delete set null,
  meta jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

alter table public.supplies enable row level security;
alter table public.audit_log enable row level security;

drop policy if exists supplies_admin_all on public.supplies;
drop policy if exists audit_admin_all on public.audit_log;

create policy supplies_admin_all on public.supplies
for all to authenticated
using (exists (select 1 from public.profiles p where p.id = auth.uid() and lower(coalesce(p.role,''))='admin'))
with check (exists (select 1 from public.profiles p where p.id = auth.uid() and lower(coalesce(p.role,''))='admin'));

create policy audit_admin_all on public.audit_log
for all to authenticated
using (exists (select 1 from public.profiles p where p.id = auth.uid() and lower(coalesce(p.role,''))='admin'))
with check (exists (select 1 from public.profiles p where p.id = auth.uid() and lower(coalesce(p.role,''))='admin'));
