create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text,
  color text default 'var(--accent-3)',
  created_at timestamptz default now()
);

create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  contact text,
  phone text,
  created_at timestamptz default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  client text not null,
  product_id bigint references public.products(id) on delete set null,
  qty integer not null default 1,
  status text not null default 'new',
  priority text not null default 'normal',
  address text,
  note text,
  created_at timestamptz default now()
);

alter table public.products add column if not exists cat_id bigint references public.categories(id) on delete set null;
alter table public.products add column if not exists supplier_id bigint references public.suppliers(id) on delete set null;

alter table public.categories enable row level security;
alter table public.suppliers enable row level security;
alter table public.orders enable row level security;

drop policy if exists categories_admin_all on public.categories;
drop policy if exists suppliers_admin_all on public.suppliers;
drop policy if exists orders_admin_all on public.orders;

create policy categories_admin_all on public.categories
for all to authenticated
using (exists (select 1 from public.profiles p where p.id = auth.uid() and lower(coalesce(p.role,''))='admin'))
with check (exists (select 1 from public.profiles p where p.id = auth.uid() and lower(coalesce(p.role,''))='admin'));

create policy suppliers_admin_all on public.suppliers
for all to authenticated
using (exists (select 1 from public.profiles p where p.id = auth.uid() and lower(coalesce(p.role,''))='admin'))
with check (exists (select 1 from public.profiles p where p.id = auth.uid() and lower(coalesce(p.role,''))='admin'));

create policy orders_admin_all on public.orders
for all to authenticated
using (exists (select 1 from public.profiles p where p.id = auth.uid() and lower(coalesce(p.role,''))='admin'))
with check (exists (select 1 from public.profiles p where p.id = auth.uid() and lower(coalesce(p.role,''))='admin'));
